services:
  db:
    build:
      context: /database
      dockerfile: Dockerfile
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: logsdb
    ports:
      - 5432:5432
    healthcheck:
       test: ["CMD-SHELL", "pg_isready", "-U", "admin"]
       interval: 5s
       retries: 3

  seed:
    build:
      context: /data_generating
      dockerfile: Dockerfile
    container_name: seed_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: logsdb
      DB_PORT: 5432
      DB_HOST: database
    depends_on:
      db:
        condition: service_healthy


